# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Travail\EFS\Travail accreditation\SQ\Developpement Informatique\Afficheur-V0.1\GUI\afficheurs.ui'
#
# Created: Fri Dec  5 11:49:01 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(982, 769)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, 30, -1, -1)
        self.formLayout.setVerticalSpacing(29)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_16 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.comboBox_cmr = QtGui.QComboBox(self.tab)
        self.comboBox_cmr.setEditable(True)
        self.comboBox_cmr.setObjectName(_fromUtf8("comboBox_cmr"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_cmr)
        self.label_31 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_31)
        self.comboBox_famille_afficheur = QtGui.QComboBox(self.tab)
        self.comboBox_famille_afficheur.setEnabled(True)
        self.comboBox_famille_afficheur.setMouseTracking(True)
        self.comboBox_famille_afficheur.setEditable(False)
        self.comboBox_famille_afficheur.setObjectName(_fromUtf8("comboBox_famille_afficheur"))
        self.comboBox_famille_afficheur.addItem(_fromUtf8(""))
        self.comboBox_famille_afficheur.addItem(_fromUtf8(""))
        self.comboBox_famille_afficheur.addItem(_fromUtf8(""))
        self.comboBox_famille_afficheur.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_famille_afficheur)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.comboBox_identification = QtGui.QComboBox(self.tab)
        self.comboBox_identification.setEnabled(True)
        self.comboBox_identification.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_identification.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_identification.setMouseTracking(True)
        self.comboBox_identification.setAcceptDrops(True)
        self.comboBox_identification.setEditable(True)
        self.comboBox_identification.setObjectName(_fromUtf8("comboBox_identification"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_identification)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.dateEdit = QtGui.QDateEdit(self.tab)
        self.dateEdit.setMinimumSize(QtCore.QSize(206, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dateEdit.setDate(QtCore.QDate(2014, 1, 1))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.dateEdit)
        self.label_13 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_13)
        self.textEdit_n_serie = QtGui.QTextEdit(self.tab)
        self.textEdit_n_serie.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_n_serie.setObjectName(_fromUtf8("textEdit_n_serie"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.textEdit_n_serie)
        self.label_17 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_17)
        self.comboBox_ident_etalon = QtGui.QComboBox(self.tab)
        self.comboBox_ident_etalon.setObjectName(_fromUtf8("comboBox_ident_etalon"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.comboBox_ident_etalon)
        self.label_32 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_32)
        self.comboBox_ce_etal = QtGui.QComboBox(self.tab)
        self.comboBox_ce_etal.setObjectName(_fromUtf8("comboBox_ce_etal"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.comboBox_ce_etal)
        self.label_30 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_30)
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.lineEdit_constructeur = QtGui.QLineEdit(self.tab)
        self.lineEdit_constructeur.setObjectName(_fromUtf8("lineEdit_constructeur"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_constructeur)
        self.label_33 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_type = QtGui.QLineEdit(self.tab)
        self.lineEdit_type.setObjectName(_fromUtf8("lineEdit_type"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_type)
        self.label_34 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_34)
        self.textEdit_renseignement_complementaire = QtGui.QTextEdit(self.tab)
        self.textEdit_renseignement_complementaire.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_renseignement_complementaire.setObjectName(_fromUtf8("textEdit_renseignement_complementaire"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.textEdit_renseignement_complementaire)
        self.label_35 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_35)
        self.textEdit_commentaire = QtGui.QTextEdit(self.tab)
        self.textEdit_commentaire.setObjectName(_fromUtf8("textEdit_commentaire"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.textEdit_commentaire)
        self.label_36 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_36)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.doubleSpinBox_resolution = QtGui.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_resolution.setMaximum(2.0)
        self.doubleSpinBox_resolution.setSingleStep(0.1)
        self.doubleSpinBox_resolution.setProperty("value", 0.1)
        self.doubleSpinBox_resolution.setObjectName(_fromUtf8("doubleSpinBox_resolution"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_resolution)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_EMT = QtGui.QComboBox(self.tab_2)
        self.comboBox_EMT.setEnabled(True)
        self.comboBox_EMT.setEditable(True)
        self.comboBox_EMT.setObjectName(_fromUtf8("comboBox_EMT"))
        self.horizontalLayout_3.addWidget(self.comboBox_EMT)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_moyenne_etalon = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_moyenne_etalon.setObjectName(_fromUtf8("lineEdit_moyenne_etalon"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_etalon)
        self.label_4 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_moyenne_afficheur = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_moyenne_afficheur.setObjectName(_fromUtf8("lineEdit_moyenne_afficheur"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_afficheur)
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_correction = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_correction.setObjectName(_fromUtf8("lineEdit_correction"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_correction)
        self.label_6 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_ecartype = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_ecartype.setObjectName(_fromUtf8("lineEdit_ecartype"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_ecartype)
        self.label_8 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_incertitude = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_incertitude.setObjectName(_fromUtf8("lineEdit_incertitude"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_incertitude)
        self.label_9 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_conformite = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_conformite.setObjectName(_fromUtf8("lineEdit_conformite"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_conformite)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_3.setFont(font)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.doubleSpinBox_resolution_2 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_resolution_2.setMaximum(2.0)
        self.doubleSpinBox_resolution_2.setSingleStep(0.1)
        self.doubleSpinBox_resolution_2.setProperty("value", 0.1)
        self.doubleSpinBox_resolution_2.setObjectName(_fromUtf8("doubleSpinBox_resolution_2"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_resolution_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.comboBox_EMT_2 = QtGui.QComboBox(self.tab_3)
        self.comboBox_EMT_2.setEditable(True)
        self.comboBox_EMT_2.setObjectName(_fromUtf8("comboBox_EMT_2"))
        self.horizontalLayout_5.addWidget(self.comboBox_EMT_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_moyenne_etalon_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_moyenne_etalon_2.setObjectName(_fromUtf8("lineEdit_moyenne_etalon_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_etalon_2)
        self.label_15 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_moyenne_afficheur_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_moyenne_afficheur_2.setObjectName(_fromUtf8("lineEdit_moyenne_afficheur_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_afficheur_2)
        self.label_18 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_correction_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_correction_2.setObjectName(_fromUtf8("lineEdit_correction_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_correction_2)
        self.label_19 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_ecartype_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_ecartype_2.setObjectName(_fromUtf8("lineEdit_ecartype_2"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_ecartype_2)
        self.label_20 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_incertitude_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_incertitude_2.setObjectName(_fromUtf8("lineEdit_incertitude_2"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_incertitude_2)
        self.label_21 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_conformite_2 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_conformite_2.setObjectName(_fromUtf8("lineEdit_conformite_2"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_conformite_2)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_4.setFont(font)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.doubleSpinBox_resolution_3 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_resolution_3.setMaximum(2.0)
        self.doubleSpinBox_resolution_3.setSingleStep(0.1)
        self.doubleSpinBox_resolution_3.setProperty("value", 0.1)
        self.doubleSpinBox_resolution_3.setObjectName(_fromUtf8("doubleSpinBox_resolution_3"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_resolution_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_7.addWidget(self.label_23)
        self.comboBox_EMT_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_EMT_3.setEditable(True)
        self.comboBox_EMT_3.setObjectName(_fromUtf8("comboBox_EMT_3"))
        self.horizontalLayout_7.addWidget(self.comboBox_EMT_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.tableWidget_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_moyenne_etalon_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_moyenne_etalon_3.setObjectName(_fromUtf8("lineEdit_moyenne_etalon_3"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_etalon_3)
        self.label_25 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_moyenne_afficheur_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_moyenne_afficheur_3.setObjectName(_fromUtf8("lineEdit_moyenne_afficheur_3"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_moyenne_afficheur_3)
        self.label_26 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_correction_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_correction_3.setObjectName(_fromUtf8("lineEdit_correction_3"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_correction_3)
        self.label_27 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_ecartype_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_ecartype_3.setObjectName(_fromUtf8("lineEdit_ecartype_3"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_ecartype_3)
        self.label_28 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_incertitude_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_incertitude_3.setObjectName(_fromUtf8("lineEdit_incertitude_3"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_incertitude_3)
        self.label_29 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_conformite_3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_conformite_3.setObjectName(_fromUtf8("lineEdit_conformite_3"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_conformite_3)
        self.verticalLayout_5.addLayout(self.formLayout_4)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuMenu.setFont(font)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionCreation = QtGui.QAction(MainWindow)
        self.actionCreation.setObjectName(_fromUtf8("actionCreation"))
        self.actionEnregistrement = QtGui.QAction(MainWindow)
        self.actionEnregistrement.setObjectName(_fromUtf8("actionEnregistrement"))
        self.actionModification = QtGui.QAction(MainWindow)
        self.actionModification.setObjectName(_fromUtf8("actionModification"))
        self.menuMenu.addAction(self.actionCreation)
        self.menuMenu.addAction(self.actionEnregistrement)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">CMR</span></p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>Famille Afficheur</p></body></html>", None))
        self.comboBox_famille_afficheur.setItemText(0, _translate("MainWindow", "Sonde alarme température", None))
        self.comboBox_famille_afficheur.setItemText(1, _translate("MainWindow", "Afficheur de température", None))
        self.comboBox_famille_afficheur.setItemText(2, _translate("MainWindow", "Afficheur de temps", None))
        self.comboBox_famille_afficheur.setItemText(3, _translate("MainWindow", "Afficheur de vitesse", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Identification Afficheur</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Date Etalonnage</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">N° Serie</span></p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Identification Etalon</p></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">N°Certificat Polynome</span></p></body></html>", None))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Nombre point contrôle</p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "Constructeur", None))
        self.label_34.setText(_translate("MainWindow", "Type", None))
        self.label_35.setText(_translate("MainWindow", "Renseignement complementaire", None))
        self.label_36.setText(_translate("MainWindow", "Commentaire", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration", None))
        self.label.setText(_translate("MainWindow", "Resolution", None))
        self.label_2.setText(_translate("MainWindow", "EMT", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Etalon", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etalon corrigé", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Afficheur", None))
        self.label_3.setText(_translate("MainWindow", "Moyenne Etalon", None))
        self.label_4.setText(_translate("MainWindow", "Moyenne Afficheur", None))
        self.label_5.setText(_translate("MainWindow", "Correction moyenne", None))
        self.label_6.setText(_translate("MainWindow", "Ecart type", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">k=2</span></p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "Conformite", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pt_1", None))
        self.label_10.setText(_translate("MainWindow", "Resolution", None))
        self.label_12.setText(_translate("MainWindow", "EMT", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Etalon", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etalon corrigé", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Afficheur", None))
        self.label_14.setText(_translate("MainWindow", "Moyenne Etalon", None))
        self.label_15.setText(_translate("MainWindow", "Moyenne Afficheur", None))
        self.label_18.setText(_translate("MainWindow", "Correction moyenne", None))
        self.label_19.setText(_translate("MainWindow", "Ecart type", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">k=2</span></p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "Conformite", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Pt_2", None))
        self.label_22.setText(_translate("MainWindow", "Resolution", None))
        self.label_23.setText(_translate("MainWindow", "EMT", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Etalon", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etalon corrigé", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Afficheur", None))
        self.label_24.setText(_translate("MainWindow", "Moyenne Etalon", None))
        self.label_25.setText(_translate("MainWindow", "Moyenne Afficheur", None))
        self.label_26.setText(_translate("MainWindow", "Correction moyenne", None))
        self.label_27.setText(_translate("MainWindow", "Ecart type", None))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">k=2</span></p></body></html>", None))
        self.label_29.setText(_translate("MainWindow", "Conformite", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Pt_3", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionCreation.setText(_translate("MainWindow", "Creation", None))
        self.actionEnregistrement.setText(_translate("MainWindow", "Enregistrement", None))
        self.actionModification.setText(_translate("MainWindow", "Modification", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

